
package Utils;

public enum ErrorCode {
    VAR_NOT_DECLARED,
    VAR_MAYBE_UNINITIALIZED,
    VAR_DECLARED_NEVER_USED,

    TYPE_MISMATCH_DECLARATION,
    TYPE_MISMATCH_ASSIGNMENT,
    TYPE_MISMATCH_RETURN,
    ARITHMETIC_REQUIRES_INT,
    COMPARISON_REQUIRES_INT,
    LOGICAL_REQUIRES_BOOL,
    UNARY_MINUS_REQUIRES_INT,
    NOT_REQUIRES_BOOL,
    PLUS_INVALID_TYPES,

    IF_CONDITION_NOT_BOOL,
    WHILE_CONDITION_NOT_BOOL,
    DO_WHILE_CONDITION_NOT_BOOL,
    FOR_CONDITION_NOT_BOOL,

    FUNCTION_NOT_DECLARED,
    NOT_A_FUNCTION,
    FUNCTION_ARG_COUNT_MISMATCH,
    FUNCTION_MUST_RETURN_VALUE,
    FUNCTION_VOID_CANNOT_RETURN_VALUE,
    RETURN_OUTSIDE_FUNCTION,
    CANNOT_COMPARE_TYPES
}
